"""initial scoring-slice schema

Revision ID: 2872a8034bb6
Revises: 
Create Date: 2026-07-21 04:33:34.739612
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2872a8034bb6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mapping_version', sa.String(length=32), nullable=False),
    sa.Column('canonical_concept', sa.String(length=128), nullable=False),
    sa.Column('source_taxonomy', sa.String(length=32), nullable=False),
    sa.Column('source_concept', sa.String(length=128), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mapping_version', 'canonical_concept', 'source_taxonomy', 'source_concept', name='uq_concept_mappings_version_key')
    )
    op.create_index(op.f('ix_concept_mappings_canonical_concept'), 'concept_mappings', ['canonical_concept'], unique=False)
    op.create_index(op.f('ix_concept_mappings_mapping_version'), 'concept_mappings', ['mapping_version'], unique=False)
    op.create_table('issuers',
    sa.Column('cik', sa.String(length=10), nullable=False),
    sa.Column('ticker', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('is_financial_sector', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('cik')
    )
    op.create_index(op.f('ix_issuers_ticker'), 'issuers', ['ticker'], unique=False)
    op.create_table('filings',
    sa.Column('accession_number', sa.String(length=25), nullable=False),
    sa.Column('issuer_cik', sa.String(length=10), nullable=False),
    sa.Column('form_type', sa.String(length=12), nullable=False),
    sa.Column('filing_date', sa.Date(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_end', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_cik'], ['issuers.cik'], ),
    sa.PrimaryKeyConstraint('accession_number')
    )
    op.create_index(op.f('ix_filings_issuer_cik'), 'filings', ['issuer_cik'], unique=False)
    op.create_table('raw_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('accession_number', sa.String(length=25), nullable=False),
    sa.Column('taxonomy', sa.String(length=32), nullable=False),
    sa.Column('concept', sa.String(length=128), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('period_start', sa.Date(), nullable=True),
    sa.Column('period_end', sa.Date(), nullable=True),
    sa.Column('value', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=True),
    sa.Column('dimensions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accession_number'], ['filings.accession_number'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('accession_number', 'content_hash', name='uq_raw_facts_accession_hash')
    )
    op.create_index(op.f('ix_raw_facts_accession_number'), 'raw_facts', ['accession_number'], unique=False)
    op.create_index(op.f('ix_raw_facts_concept'), 'raw_facts', ['concept'], unique=False)
    op.create_table('score_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issuer_cik', sa.String(length=10), nullable=False),
    sa.Column('model', sa.Enum('piotroski', 'altman', 'beneish', 'sloan', name='model', native_enum=False, length=16), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('formula_version', sa.String(length=32), nullable=False),
    sa.Column('accession_number', sa.String(length=25), nullable=False),
    sa.Column('aggregate_value', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('applicability', sa.Enum('computed', 'excluded_out_of_scope', 'computed_with_caveat', name='applicability', native_enum=False, length=24), nullable=False),
    sa.Column('superseded', sa.Boolean(), nullable=False),
    sa.Column('superseded_by', sa.UUID(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accession_number'], ['filings.accession_number'], ),
    sa.ForeignKeyConstraint(['issuer_cik'], ['issuers.cik'], ),
    sa.ForeignKeyConstraint(['superseded_by'], ['score_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_runs_fiscal_year'), 'score_runs', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_score_runs_issuer_cik'), 'score_runs', ['issuer_cik'], unique=False)
    op.create_table('canonical_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issuer_cik', sa.String(length=10), nullable=False),
    sa.Column('accession_number', sa.String(length=25), nullable=False),
    sa.Column('canonical_concept', sa.String(length=128), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('mapping_version', sa.String(length=32), nullable=False),
    sa.Column('selected_from_raw_fact_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accession_number'], ['filings.accession_number'], ),
    sa.ForeignKeyConstraint(['issuer_cik'], ['issuers.cik'], ),
    sa.ForeignKeyConstraint(['selected_from_raw_fact_id'], ['raw_facts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuer_cik', 'canonical_concept', 'fiscal_year', 'mapping_version', name='uq_canonical_facts_key')
    )
    op.create_index(op.f('ix_canonical_facts_canonical_concept'), 'canonical_facts', ['canonical_concept'], unique=False)
    op.create_index(op.f('ix_canonical_facts_fiscal_year'), 'canonical_facts', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_canonical_facts_issuer_cik'), 'canonical_facts', ['issuer_cik'], unique=False)
    op.create_table('score_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('score_run_id', sa.UUID(), nullable=False),
    sa.Column('model', sa.Enum('piotroski', 'altman', 'beneish', 'sloan', name='model', native_enum=False, length=16), nullable=False),
    sa.Column('signal_key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('status', sa.Enum('pass_', 'fail', 'insufficient_data', name='signalstatus', native_enum=False, length=24), nullable=False),
    sa.Column('band_label', sa.String(length=48), nullable=True),
    sa.Column('threshold_ref', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['score_run_id'], ['score_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('score_run_id', 'signal_key', name='uq_score_results_run_signal')
    )
    op.create_index(op.f('ix_score_results_score_run_id'), 'score_results', ['score_run_id'], unique=False)
    op.create_table('data_quality_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('accession_number', sa.String(length=25), nullable=True),
    sa.Column('canonical_fact_id', sa.UUID(), nullable=True),
    sa.Column('issue_type', sa.String(length=64), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('needs_review', 'resolved', 'dismissed', name='issuestatus', native_enum=False, length=16), nullable=False),
    sa.Column('raised_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['accession_number'], ['filings.accession_number'], ),
    sa.ForeignKeyConstraint(['canonical_fact_id'], ['canonical_facts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_inputs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('score_run_id', sa.UUID(), nullable=False),
    sa.Column('signal_key', sa.String(length=64), nullable=False),
    sa.Column('canonical_fact_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['canonical_fact_id'], ['canonical_facts.id'], ),
    sa.ForeignKeyConstraint(['score_run_id'], ['score_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_score_inputs_score_run_id'), 'score_inputs', ['score_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_score_inputs_score_run_id'), table_name='score_inputs')
    op.drop_table('score_inputs')
    op.drop_table('data_quality_issues')
    op.drop_index(op.f('ix_score_results_score_run_id'), table_name='score_results')
    op.drop_table('score_results')
    op.drop_index(op.f('ix_canonical_facts_issuer_cik'), table_name='canonical_facts')
    op.drop_index(op.f('ix_canonical_facts_fiscal_year'), table_name='canonical_facts')
    op.drop_index(op.f('ix_canonical_facts_canonical_concept'), table_name='canonical_facts')
    op.drop_table('canonical_facts')
    op.drop_index(op.f('ix_score_runs_issuer_cik'), table_name='score_runs')
    op.drop_index(op.f('ix_score_runs_fiscal_year'), table_name='score_runs')
    op.drop_table('score_runs')
    op.drop_index(op.f('ix_raw_facts_concept'), table_name='raw_facts')
    op.drop_index(op.f('ix_raw_facts_accession_number'), table_name='raw_facts')
    op.drop_table('raw_facts')
    op.drop_index(op.f('ix_filings_issuer_cik'), table_name='filings')
    op.drop_table('filings')
    op.drop_index(op.f('ix_issuers_ticker'), table_name='issuers')
    op.drop_table('issuers')
    op.drop_index(op.f('ix_concept_mappings_mapping_version'), table_name='concept_mappings')
    op.drop_index(op.f('ix_concept_mappings_canonical_concept'), table_name='concept_mappings')
    op.drop_table('concept_mappings')
    # ### end Alembic commands ###
