"""add market_prices and score_inputs.market_price_id

Revision ID: 65237ddc23a0
Revises: 2872a8034bb6
Create Date: 2026-07-21 04:51:42.756580
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '65237ddc23a0'
down_revision: Union[str, None] = '2872a8034bb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issuer_cik', sa.String(length=10), nullable=False),
    sa.Column('price_date', sa.Date(), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=28, scale=6), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_cik'], ['issuers.cik'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuer_cik', 'price_date', 'source', name='uq_market_prices_key')
    )
    op.create_index(op.f('ix_market_prices_issuer_cik'), 'market_prices', ['issuer_cik'], unique=False)
    op.add_column('score_inputs', sa.Column('market_price_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'score_inputs', 'market_prices', ['market_price_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'score_inputs', type_='foreignkey')
    op.drop_column('score_inputs', 'market_price_id')
    op.drop_index(op.f('ix_market_prices_issuer_cik'), table_name='market_prices')
    op.drop_table('market_prices')
    # ### end Alembic commands ###
