"""add issuers.is_capital_intensive

Revision ID: 66fdb674356b
Revises: 65237ddc23a0
Create Date: 2026-07-21 04:55:16.757331
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '66fdb674356b'
down_revision: Union[str, None] = '65237ddc23a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issuers', sa.Column('is_capital_intensive', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issuers', 'is_capital_intensive')
    # ### end Alembic commands ###
