"""add reverse_dcf_runs and reverse_dcf_cells

Materializes the reverse DCF so the read path stops computing it (AD-1). Before
this, `reverse_dcf_for_issuer` had one caller and it was `api/repository.py` on the
read path, so every page load re-solved the DCF and all 35 sensitivity cells.

Cells are their own table rather than a JSONB column on the run: an implied growth
rate is a financial figure and AD-15 requires NUMERIC. Rates carry scale 10 because
the solver's tolerance is 1e-7, so the money-shaped NUMERIC(28, 6) used elsewhere
would round the answer coarser than the bisection that produced it.

Revision ID: b43d7bd6fe33
Revises: b2d5f8c1a334
Create Date: 2026-08-13 06:16:02.134950
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'b43d7bd6fe33'
down_revision: Union[str, None] = 'b2d5f8c1a334'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reverse_dcf_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('issuer_cik', sa.String(length=10), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('spec_version', sa.String(length=32), nullable=False),
    sa.Column('implied_growth', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('insufficient_data', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.Column('enterprise_value', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('market_cap', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('total_debt', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('cash_and_equivalents', sa.Numeric(precision=28, scale=6), nullable=True),
    sa.Column('discount_rate', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('terminal_growth', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('horizon_years', sa.Integer(), nullable=False),
    sa.Column('caveats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('attribution', sa.String(length=1024), nullable=False),
    sa.Column('market_price_date', sa.Date(), nullable=True),
    sa.Column('market_price_source', sa.String(length=32), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=18, scale=8), nullable=True),
    sa.Column('fx_rate_date', sa.Date(), nullable=True),
    sa.Column('fx_rate_source', sa.String(length=32), nullable=True),
    sa.Column('has_grid', sa.Boolean(), nullable=False),
    sa.Column('grid_low', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('grid_high', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('resolved_cells', sa.Integer(), nullable=False),
    sa.Column('total_cells', sa.Integer(), nullable=False),
    sa.Column('historical_revenue_cagr', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('historical_from_fiscal_year', sa.Integer(), nullable=True),
    sa.Column('historical_to_fiscal_year', sa.Integer(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['issuer_cik'], ['issuers.cik'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('issuer_cik', 'fiscal_year', 'spec_version', name='uq_reverse_dcf_runs_key')
    )
    op.create_index(op.f('ix_reverse_dcf_runs_fiscal_year'), 'reverse_dcf_runs', ['fiscal_year'], unique=False)
    op.create_index(op.f('ix_reverse_dcf_runs_issuer_cik'), 'reverse_dcf_runs', ['issuer_cik'], unique=False)
    op.create_table('reverse_dcf_cells',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reverse_dcf_run_id', sa.UUID(), nullable=False),
    sa.Column('discount_rate', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('terminal_growth', sa.Numeric(precision=18, scale=10), nullable=False),
    sa.Column('implied_growth', sa.Numeric(precision=18, scale=10), nullable=True),
    sa.Column('reason', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['reverse_dcf_run_id'], ['reverse_dcf_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reverse_dcf_run_id', 'discount_rate', 'terminal_growth', name='uq_reverse_dcf_cells_key')
    )
    op.create_index(op.f('ix_reverse_dcf_cells_reverse_dcf_run_id'), 'reverse_dcf_cells', ['reverse_dcf_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reverse_dcf_cells_reverse_dcf_run_id'), table_name='reverse_dcf_cells')
    op.drop_table('reverse_dcf_cells')
    op.drop_index(op.f('ix_reverse_dcf_runs_issuer_cik'), table_name='reverse_dcf_runs')
    op.drop_index(op.f('ix_reverse_dcf_runs_fiscal_year'), table_name='reverse_dcf_runs')
    op.drop_table('reverse_dcf_runs')
    # ### end Alembic commands ###
