"""add fx_rates table and score_inputs.fx_rate_id for Altman currency fix

Revision ID: bd927201da21
Revises: d78002f0f127
Create Date: 2026-07-23 05:38:53.963055
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bd927201da21'
down_revision: Union[str, None] = 'd78002f0f127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('currency_pair', sa.String(length=8), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('rate', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_pair', 'rate_date', 'source', name='uq_fx_rates_key')
    )
    op.create_index(op.f('ix_fx_rates_currency_pair'), 'fx_rates', ['currency_pair'], unique=False)
    op.add_column('score_inputs', sa.Column('fx_rate_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'score_inputs', 'fx_rates', ['fx_rate_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'score_inputs', type_='foreignkey')
    op.drop_column('score_inputs', 'fx_rate_id')
    op.drop_index(op.f('ix_fx_rates_currency_pair'), table_name='fx_rates')
    op.drop_table('fx_rates')
    # ### end Alembic commands ###
