"""widen raw_facts.concept to 256 chars for real XBRL extension tags

Revision ID: d78002f0f127
Revises: 66fdb674356b
Create Date: 2026-07-21 19:53:45.773553
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd78002f0f127'
down_revision: Union[str, None] = '66fdb674356b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_facts', 'concept',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=256),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_facts', 'concept',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
    # ### end Alembic commands ###
